enum MessageId {
    // base validate
    VALIDATE_OBJECT_NOT_FOUND = "VALIDATE_OBJECT_NOT_FOUND",
    VALIDATE_URL_REQUIRED = "VALIDATE_URL_REQUIRED",
    VALIDATE_LIMIT_MORE_THAN_1 = "VALIDATE_LIMIT_MORE_THAN_1",
    VALIDATE_PAGE_MORE_THAN_1 = "VALIDATE_PAGE_MORE_THAN_1",
    VALIDATE_ID_REQUIRED = "VALIDATE_ID_REQUIRED",
    VALIDATE_ID_MIN_24 = "VALIDATE_ID_MIN_24",
    VALIDATE_ID_MAX_24 = "VALIDATE_ID_MAX_24",
    VALIDATE_ID_NOT_MATCH_WITH_FORMAT = "VALIDATE_ID_NOT_MATCH_WITH_FORMAT",
    VALIDATE_FILE_REQUIRED = "VALIDATE_FILE_REQUIRED",
    VALIDATE_FIRST_NAME_REQUIRED = "VALIDATE_FIRST_NAME_REQUIRED",
    VALIDATE_LAST_NAME_REQUIRED = "VALIDATE_LAST_NAME_REQUIRED",
    VALIDATE_PASSWORD_REQUIRED = "VALIDATE_PASSWORD_REQUIRED",
    VALIDATE_EMAIL_REQUIRED = "VALIDATE_EMAIL_REQUIRED",

    // data message
    EMAIL_IS_EXIST = "EMAIL_IS_EXIST",
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
    VALIDATE_EMAIL_NOT_MATCH_FORMAT = "VALIDATE_EMAIL_NOT_MATCH_FORMAT",
    PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH",
    VALIDATE_PASSWORD_MIN = 'VALIDATE_PASSWORD_MIN',
    VALIDATE_PASSWORD_MAX = 'VALIDATE_PASSWORD_MAX',
    VALIDATE_NAME_REQUIRED = 'VALIDATE_NAME_REQUIRED',
    VALIDATE_USER_REQUIRED = 'VALIDATE_USER_REQUIRED',
    VALIDATE_ROLE_REQUIRED = 'VALIDATE_ROLE_REQUIRED'
}

export default MessageId;